
package org.example.readservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionByNameService", targetNamespace = "http://readservice/", wsdlLocation = "http://localhost:1090/transactions?wsdl")
public class TransactionByNameService
    extends Service
{

    private final static URL TRANSACTIONBYNAMESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONBYNAMESERVICE_EXCEPTION;
    private final static QName TRANSACTIONBYNAMESERVICE_QNAME = new QName("http://readservice/", "TransactionByNameService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1090/transactions?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONBYNAMESERVICE_WSDL_LOCATION = url;
        TRANSACTIONBYNAMESERVICE_EXCEPTION = e;
    }

    public TransactionByNameService() {
        super(__getWsdlLocation(), TRANSACTIONBYNAMESERVICE_QNAME);
    }

    public TransactionByNameService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONBYNAMESERVICE_QNAME, features);
    }

    public TransactionByNameService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONBYNAMESERVICE_QNAME);
    }

    public TransactionByNameService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONBYNAMESERVICE_QNAME, features);
    }

    public TransactionByNameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionByNameService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransactionByName
     */
    @WebEndpoint(name = "TransactionByNamePort")
    public TransactionByName getTransactionByNamePort() {
        return super.getPort(new QName("http://readservice/", "TransactionByNamePort"), TransactionByName.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransactionByName
     */
    @WebEndpoint(name = "TransactionByNamePort")
    public TransactionByName getTransactionByNamePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://readservice/", "TransactionByNamePort"), TransactionByName.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONBYNAMESERVICE_EXCEPTION!= null) {
            throw TRANSACTIONBYNAMESERVICE_EXCEPTION;
        }
        return TRANSACTIONBYNAMESERVICE_WSDL_LOCATION;
    }

}
