//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.31 at 04:50:04 PM IST 
//


package services.transactions;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.transactions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.transactions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateRemarksResponse }
     * 
     */
    public UpdateRemarksResponse createUpdateRemarksResponse() {
        return new UpdateRemarksResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link Transactions }
     * 
     */
    public Transactions createTransactions() {
        return new Transactions();
    }

    /**
     * Create an instance of {@link AddTransactionResponse }
     * 
     */
    public AddTransactionResponse createAddTransactionResponse() {
        return new AddTransactionResponse();
    }

    /**
     * Create an instance of {@link SenderResponse }
     * 
     */
    public SenderResponse createSenderResponse() {
        return new SenderResponse();
    }

    /**
     * Create an instance of {@link AddTransactionRequest }
     * 
     */
    public AddTransactionRequest createAddTransactionRequest() {
        return new AddTransactionRequest();
    }

    /**
     * Create an instance of {@link ReceiverResponse }
     * 
     */
    public ReceiverResponse createReceiverResponse() {
        return new ReceiverResponse();
    }

    /**
     * Create an instance of {@link AmountResponse }
     * 
     */
    public AmountResponse createAmountResponse() {
        return new AmountResponse();
    }

    /**
     * Create an instance of {@link ReceiverRequest }
     * 
     */
    public ReceiverRequest createReceiverRequest() {
        return new ReceiverRequest();
    }

    /**
     * Create an instance of {@link UpdateRemarksRequest }
     * 
     */
    public UpdateRemarksRequest createUpdateRemarksRequest() {
        return new UpdateRemarksRequest();
    }

    /**
     * Create an instance of {@link DeleteDatesRequest }
     * 
     */
    public DeleteDatesRequest createDeleteDatesRequest() {
        return new DeleteDatesRequest();
    }

    /**
     * Create an instance of {@link AmountRequest }
     * 
     */
    public AmountRequest createAmountRequest() {
        return new AmountRequest();
    }

    /**
     * Create an instance of {@link DeleteDatesResponse }
     * 
     */
    public DeleteDatesResponse createDeleteDatesResponse() {
        return new DeleteDatesResponse();
    }

    /**
     * Create an instance of {@link SenderRequest }
     * 
     */
    public SenderRequest createSenderRequest() {
        return new SenderRequest();
    }

}
