
package soappractice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "practiceService", targetNamespace = "http://SoapPractice/", wsdlLocation = "http://localhost:1000/shreya?wsdl")
public class PracticeService
    extends Service
{

    private final static URL PRACTICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRACTICESERVICE_EXCEPTION;
    private final static QName PRACTICESERVICE_QNAME = new QName("http://SoapPractice/", "practiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1000/shreya?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRACTICESERVICE_WSDL_LOCATION = url;
        PRACTICESERVICE_EXCEPTION = e;
    }

    public PracticeService() {
        super(__getWsdlLocation(), PRACTICESERVICE_QNAME);
    }

    public PracticeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRACTICESERVICE_QNAME, features);
    }

    public PracticeService(URL wsdlLocation) {
        super(wsdlLocation, PRACTICESERVICE_QNAME);
    }

    public PracticeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRACTICESERVICE_QNAME, features);
    }

    public PracticeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PracticeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Practice
     */
    @WebEndpoint(name = "practicePort")
    public Practice getPracticePort() {
        return super.getPort(new QName("http://SoapPractice/", "practicePort"), Practice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Practice
     */
    @WebEndpoint(name = "practicePort")
    public Practice getPracticePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SoapPractice/", "practicePort"), Practice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRACTICESERVICE_EXCEPTION!= null) {
            throw PRACTICESERVICE_EXCEPTION;
        }
        return PRACTICESERVICE_WSDL_LOCATION;
    }

}
