package org.example.dao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SOAPServiceService", targetNamespace = "http://dao.soap/", wsdlLocation = "http://localhost:1234/Account?wsdl")
public class serviceSoapService
        extends Service
{

    private final static URL SERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESOAPSERVICE_EXCEPTION;
    private final static QName SERVICESOAPSERVICE_QNAME = new QName("http://dao.soap/", "ServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/Account?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESOAPSERVICE_WSDL_LOCATION = url;
        SERVICESOAPSERVICE_EXCEPTION = e;
    }

    public serviceSoapService() {
        super(__getWsdlLocation(), SERVICESOAPSERVICE_QNAME);
    }

    public serviceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESOAPSERVICE_QNAME, features);
    }

    public serviceSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESOAPSERVICE_QNAME);
    }

    public serviceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESOAPSERVICE_QNAME, features);
    }

    public serviceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public serviceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SOAPService
     */
    @WebEndpoint(name = "SOAPServicePort")
    public soapService getSOAPServicePort() {
        return super.getPort(new QName("http://dao.soap/", "SOAPServicePort"), soapService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPService
     */
    @WebEndpoint(name = "SOAPServicePort")
    public soapService getSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.soap/", "SOAPServicePort"), soapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESOAPSERVICE_EXCEPTION!= null) {
            throw SERVICESOAPSERVICE_EXCEPTION;
        }
        return SERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
